Repository isitvegan/isitvegan-web, pull requests merged in 2019-07, with the labels that each got.

#48 Support dark mode
  client/less/components/search-result-item.less
  client/less/core/typography.less
  client/less/main.less
Labels: enhancement

#39 Add search scopes
  .gitignore
  Vagrantfile
  client/less/components/search-bar.less
  client/less/components/search-scope-bar.less
  client/less/main.less
  client/src/components/search-input.tsx
  client/src/components/search-results.tsx
  client/src/components/search-scope-bar.tsx
  client/src/main.tsx
  client/src/search-api-proxy.ts
  client/src/search-scope.tsx
  scripts/setup_vm.sh
  src/search_engine.rs
  src/server.rs
Labels: enhancement

#52 Add Footer
  client/index.html
  client/less/components/page-footer.less
  client/less/components/page-layout.less
  client/less/components/search-result-item.less
  client/less/main.less
  client/src/main.tsx
Labels: client

#55 Make footer not float on the left on large screens
  client/index.html
  client/less/components/page-footer.less
  client/less/components/search-bar.less
  client/less/components/search-result-item.less
  client/less/main.less
Labels: bug

#57 Improve placeholders
  client/src/main.tsx
Labels: client, enhancement
